{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "considerable-smart",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cloning into 'AlphaZeroForMiniGeister'...\n",
      "remote: Enumerating objects: 20, done.\u001b[K\n",
      "remote: Counting objects: 100% (20/20), done.\u001b[K\n",
      "remote: Compressing objects: 100% (16/16), done.\u001b[K\n",
      "remote: Total 155 (delta 5), reused 13 (delta 4), pack-reused 135\u001b[K\n",
      "Receiving objects: 100% (155/155), 69.95 MiB | 851.00 KiB/s, done.\n",
      "Resolving deltas: 100% (74/74), done.\n"
     ]
    }
   ],
   "source": [
    "!git clone https://github.com/keisuke-777/AlphaZeroForMiniGeister.git"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "numeric-study",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-10-078de8d6b9da>, line 3)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-10-078de8d6b9da>\"\u001b[0;36m, line \u001b[0;32m3\u001b[0m\n\u001b[0;31m    def cyfib(int n):\u001b[0m\n\u001b[0m                  ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "%load_ext Cython"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "specified-devil",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "Traceback (most recent call last):\n",
      "  File \"game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/pv_mcts.py\", line 6, in <module>\n",
      "    from game import State\n",
      "  File \"/Users/keisuke_main/研究室/研究全般/Geister/AlphaZeroForGeister/game.py\", line 229, in <module>\n",
      "    from pv_mcts import predict\n",
      "ImportError: cannot import name 'predict'\n",
      "182 ms ± 3.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)\n"
     ]
    }
   ],
   "source": [
    "%%timeit\n",
    "!python game.py"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "test",
   "language": "python",
   "name": "test"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
